// <auto-generated />
namespace p.WebUI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class _055618052014 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_055618052014));
        
        string IMigrationMetadata.Id
        {
            get { return "201405180257431_05.56.18.05.2014"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
