// <auto-generated />
namespace p.WebUI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class _170514052014 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_170514052014));
        
        string IMigrationMetadata.Id
        {
            get { return "201405141405487_17.05.14.05.2014"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
